# Generated by Django 5.1.1 on 2024-09-12 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('make', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=20)),
                ('contact_value', models.CharField(max_length=32)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_management.lead')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contacts Information',
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('specialization', models.CharField(max_length=32)),
                ('services', models.ManyToManyField(to='vehicle_management.service')),
            ],
            options={
                'verbose_name': 'Mechanic',
                'verbose_name_plural': 'Mechanics',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_management.vehicle'),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicles',
            field=models.ManyToManyField(to='vehicle_management.vehicle'),
        ),
    ]
